### PR TITLE
Added notebook authoring w/ Jupyter NBRequirements scenario

### LINKED ISSUE #9: How to solve your Jupyter Notebook dependencies automagically and with the help of cyborgs

### PR DESCRIPTION
**Pull request by CermakM**
closes #9 

ai-machine-learning/jupyter-notebooks-dependencies/

    modified:   ai-machine-learning-pathway.json
    new file:   assets/templates/notebook-builder.json
    new file:   assets/templates/notebook-deployer.yaml
    new file:   env-init.sh
    new file:   index.json
    new file:   01-authoring-a-notebook.md
    new file:   02-authoring-a-notebook-nbrequirements.md
    new file:   03-authoring-a-notebook-nbrequirements.md
    new file:   04a-authoring-a-notebook-dependencies.md
    new file:   04b-authoring-a-notebook-dependencies.md
    new file:   04c-authoring-a-notebook-dependencies.md
    new file:   05-creating-a-notebook-image.md
    new file:   index.json

/
    new file:   assets/jupyternotebooks/jupyter-notebooks-authoring-42/nbrequirements-dependencies.png
    new file:   assets/jupyternotebooks/jupyter-notebooks-authoring-42/nbrequirements-ui-logo.png
    new file:   assets/jupyternotebooks/jupyter-notebooks-authoring-42/nbrequirements-ui-unwrapped.png
    new file:   assets/jupyternotebooks/jupyter-notebooks-authoring-42/openshift-console.png

Signed-off-by: Marek Cermak <macermak@redhat.com>

### CODE REVIEW

**Comment by CermakM** [comment]
@goern

**Comment by 4n4nd** [comment]
@CermakM do you have this scenario hosted anywhere so we could just test it from your fork?

**Comment by goern** [comment]
@saisankargochhayat could you please have a look at this and merge it w/ Anand

**Comment by CermakM** [comment]
@4n4nd Yes, It's available on my Katacoda: https://www.katacoda.com/cermakm/courses/ai-machine-learning

**Pull request closed without merging**
